spring:
  application:
    name: Hotel_Booking_App

  datasource:
    url: jdbc:mysql://localhost:3306/hotel?createDatabaseIfNotExist=true
    username: root
    password: nizarIng_1983
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true  # Pretty print SQL in logs
    hibernate:
      ddl-auto: validate
    show-sql: true  # Show SQL queries in console# or update / create / create-drop depending on your needs

server:
  port: 9090

# Logging (optional, for debugging)
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
